version: '3.4'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /home/sigmoid/shree/prometheus/assignment/config:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    network_mode: host
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: host

