apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: LoadBalancer
  selector:
    app: python-app
  ports:
   - name: http 
     port: 9011
     targetPort: 9011
   - name: metrics
     port: 8011
     targetPort: 8011
